name = "workers-tunnel"
main = "build/worker/shim.mjs"
compatibility_date = "2024-09-02"

[build]
command = "cargo install -q worker-build && worker-build --release"

[observability]
enabled = true
head_sampling_rate = 1

[vars]
USER_ID = "784003ab-ecbe-439c-aeae-2ed2269771a4" # your uuid
PROXY_IP = "" # proxyip.fxxk.dedyn.io
FALLBACK_SITE = "" # https://httpbin.org/status/404
SHOW_URI = "true" # show vless uri in /UUID path
